src/CyclingTripsCore/Controllers/BrowseController.cs
using System.Linq;
using Microsoft.AspNetCore.Mvc;
using CyclingTrips.Models;
using Microsoft.EntityFrameworkCore;

namespace CyclingTrips.Controllers
{
    public class BrowseController : Controller
    {
        private ICyclingTripsRepository _repository;
        private CyclingTripsDbContext _context;

        public BrowseController(CyclingTripsDbContext context, ICyclingTripsRepository repository)
        {
            _repository = repository;
            _context = context;   
        }

        // GET: Trip
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Trip(int? id)
        {
            var trip = _context.Trips
                .Include(t => t.Stops)
                .Where(t => t.ID == id)
                .FirstOrDefault();
            return View(trip);
        }

        // GET: Trip/Details/5
        public IActionResult Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            Trip trip = _repository.GetAllTrips().Single(m => m.ID == id);
            if (trip == null)
            {
                return NotFound();
            }

            return View(trip);
        }
    }
}

src/CyclingTripsCore/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using CyclingTrips.ViewModels;
using CyclingTrips.Models;
using CyclingTripsCore.Services;

namespace CyclingTrips.Controllers
{
    public class HomeController : Controller
    {
        private ICyclingTripsRepository _repository;

        public HomeController(ICyclingTripsRepository repository)
        {
            _repository = repository;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }


        public IActionResult Error()
        {
            return View();
        }
    }
}

src/CyclingTripsCore/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="row">
    <div class="col-md-12">
        <h1>WELCOME TO CYCLING TRIPS!</h1>
        <div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="4000">
            <ol class="carousel-indicators">
                <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
                <li data-target="#myCarousel" data-slide-to="1"></li>
                <li data-target="#myCarousel" data-slide-to="2"></li>
                <li data-target="#myCarousel" data-slide-to="3"></li>
            </ol>
            <div class="carousel-inner" role="listbox">
                <div class="item active">
                    <img src="~/images/cycling1.jpg" alt="cycling" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Ride with us!

                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/cycling2.jpg" alt="Visual Studio" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Discover new Journeys
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/cycling3.jpg" alt="Package Management" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Ask the experts
                        </p>
                    </div>
                </div>
                <div class="item">
                    <img src="~/images/cycling4.jpg" alt="Microsoft Azure" class="img-responsive" />
                    <div class="carousel-caption">
                        <p>
                            Plan your next trip
                        </p>
                    </div>
                </div>
            </div>
            @*<a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
                    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
                    <span class="sr-only">Previous</span>
                </a>
                <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
                    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
                    <span class="sr-only">Next</span>
                </a>*@

        </div>

    </div>
</div>
<div class="row">

    <div class="col-md-10 col-md-offset-1">
        <ul class="list-group">
            <li class="list-group-item">
                <a asp-controller="Browse" asp-action="Index">All The Trips <i class="fa fa-angle-double-right fa-2x"></i></a>
            </li>
            @*<li class="list-group-item">
                <a>Create a new Account <i class="fa fa-chevron-right"></i></a>
            </li>*@

        </ul>
    </div>
</div>